{
    "message": "Throw 2 error in 2 code blocks",
    "errors": [
        {
            "name": "AssertionError"
        },
        {
            "name": "AssertionError"
        }
    ]
}