assert.throws(function () {
  throw new Error("error");
}); // => Error